spring:
  application:
    name: hello-server

server:
  port: 8061

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/
  instance:
    hostname: localhost